name: Regress

on: [workflow_dispatch, pull_request]

jobs:
  spelling:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fjcaetano/mint-action@v1.0.2
        with: { package: fromkk/SpellChecker }
      - name: Check spelling
        run: sh .github/scripts/checkSpell.sh

  rugby:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with: { xcode-version: '14.1' }
      - name: Build Rugby
        run: |
          swift build -c release
          path=`swift build -c release --show-bin-path`
          strip -rSTx "$path/rugby"
          echo "rugby_path=$path/rugby" >> $GITHUB_ENV
          swift run rugby --version
      - uses: actions/upload-artifact@v3
        with:
          name: rugby
          path: ${{ env.rugby_path }}
